### PR TITLE
Developed new mapping system

### PR DESCRIPTION
**Pull request by robellgabriel**
- refactored TESTGUI and Models scripts to work with networkx api
- updated readme and neighbourhood graph for new subsystem

sidenote:
- currently only works for NH, still need to implement City graph in networkx
- current changes made a good amount of functions and classes in TESTGUI and Models now obsolete, can be deleted or kept for future referencing

### CODE REVIEW

**Review by phucla0122 — COMMENTED** [review]
Looks good, but the test is not passing for github. Maybe you could try to fix it?

**Review by nicolastuttle — APPROVED** [review]
I think the tests aren't passing due to the old models API not being used anymore. I can try to fix it once this is merged, or you can try your hand @robellgabriel, let me know. Otherwise this looks good!

**Review by robellgabriel — COMMENTED** [review]
@nicolastuttle Yup that was exactly it, the current paths used for testing were saved with the old models api which saves the map coordinates as a 'Path' object but I changed it to a 'Lane" object for simplicity. Running tests on new paths should work fine, will commit this fix shortly.

**Review by robellgabriel — COMMENTED** [review]
@phucla0122 Yup will do, found out the problem as discussed with nick.

**Review by phucla0122 — APPROVED** [review]

**Pull request merged**
